version: '3'

services:
  api:
    container_name: api
    image: park-announce/pa-api
    ports:
      - 8000:8000
    depends_on:
      - db

  web:
    container_name: web
    image: park-announce/pa-web
    ports:
      - 5173:5173
    depends_on:
      - api

  db:
    container_name: db
    image: park-announce/pa-db
    ports:
      - '5432:5432'
    volumes:
      - './dbdata:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=park-announce
      - POSTGRES_PASSWORD=PosgresDb1591*
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    volumes:
      - './pgadmin-data:/var/lib/pgadmin'
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379/tcp'