version: '3'

services:
  api:
    container_name: api
    image: park-announce/pa-api
    ports:
      - 8000:8000
    depends_on:
      - kafka      
    environment:
      - PA_API_JWT_KEY=${PA_API_JWT_KEY}
      - PA_API_WEB_GOOGLE_CLIENT_ID=${PA_API_WEB_GOOGLE_CLIENT_ID}
      - PA_API_WEB_GOOGLE_CLIENT_SECRET=${PA_API_WEB_GOOGLE_CLIENT_SECRET}
      - PA_API_WEB_GOOGLE_REDIRECT_URI=${PA_API_WEB_GOOGLE_REDIRECT_URI}
      - PA_API_IOS_GOOGLE_CLIENT_ID=${PA_API_IOS_GOOGLE_CLIENT_ID}
      - PA_API_ANDROID_GOOGLE_CLIENT_ID=${PA_API_ANDROID_GOOGLE_CLIENT_ID}
  service:
    container_name: service
    image: park-announce/pa-service
    depends_on:
      - db
      - kafka    
      - redis  
  web:
    container_name: web
    image: park-announce/pa-web
    ports:
      - 5173:5173
    depends_on:
      - api
  db:
    container_name: db
    image: park-announce/pa-db
    ports:
      - '5432:5432'
    volumes:
      - './dbdata:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    volumes:
      - './pgadmin-data:/var/lib/pgadmin'
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379/tcp'
    volumes:
      - ./redis-data:/data
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    links:
      - zookeeper
    restart: always
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=${KAFKA_BROKER_ID}
      - KAFKA_ADVERTISED_HOST_NAME=${KAFKA_ADVERTISED_HOST_NAME}
      - KAFKA_ZOOKEEPER_CONNECT=${KAFKA_ZOOKEEPER_CONNECT}