version: '3'

services:
  api:
    container_name: api
    image: park-announce/pa-api
    ports:
      - 8000:8000
    depends_on:
      - kafka      
    environment:
      - PA_API_JWT_KEY=hdRZ5qVg3Eeiy8a6bgosxw
      - PA_API_WEB_GOOGLE_CLIENT_ID=411985926318-emhk771uorc6g8j86cm8ud7elk8408k2.apps.googleusercontent.com
      - PA_API_WEB_GOOGLE_CLIENT_SECRET=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
      - PA_API_WEB_GOOGLE_REDIRECT_URI=http://localhost:5173
      - PA_API_IOS_GOOGLE_CLIENT_ID=411985926318-ld5o23m1ldge5tmj56epbcdab6v5k6gv.apps.googleusercontent.com
      - PA_API_ANDROID_GOOGLE_CLIENT_ID=
  service:
    container_name: service
    image: park-announce/pa-service
    depends_on:
      - db
      - kafka      
  web:
    container_name: web
    image: park-announce/pa-web
    ports:
      - 5173:5173
    depends_on:
      - api
  db:
    container_name: db
    image: park-announce/pa-db
    ports:
      - '5432:5432'
    volumes:
      - './dbdata:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=park_announce
      - POSTGRES_PASSWORD=PosgresDb1591*
      - POSTGRES_DB=padb
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    volumes:
      - './pgadmin-data:/var/lib/pgadmin'
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379/tcp'
    volumes:
      - ./redis-data:/data
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    links:
      - zookeeper
    restart: always
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181