name: pa_mobile_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  async: ^2.9.0
  collection: ^1.16.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  http: ^1.0.0
  latlong2: ^0.9.0
  meta: ^1.8.0
  polylabel: ^1.0.1
  proj4dart: ^2.1.0
  url_launcher: ^6.1.12
  vector_math: ^2.1.2

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  test: ^1.21.4

flutter:
  uses-material-design: true